#emp info
empid=int(input("enter empid:"))
empname=input("enter empname:")
empcontact=int(input("enter contactno:"))
empaddress=input("enter empadress:")
empdepartment=input("enter departnment name:")
print("empid:",empid)
print("empname:",empname)
print("empcontact:",empcontact)
print("empaddress:",empaddress)
print("empdepartmenr:",empdepartment)

# Assignment 2 Take two numbers from the user and display:Addition Subtraction Multiplication Division Reminder
num1=int(input("enter num1:"))
num2=int(input("enter num2:"))
print("addition:",num1+num2)
print("substraction:",num1-num2)
print("multiplication:",num1*num2)
print("division:",num1/num2)
print("remainder:",num1%num2)
